with source as (

    select * from {{ source('open_food_facts_data', 'open_food_facts_parquet') }}

),
 
renamed as (
 
    select
 
        ---------- ids
        code as product_id,
 
        ---------- strings
        additives_tags,
        allergens_tags,
        brands,
        brands_tags,
        categories,
        categories_properties,
        categories_tags,
        checkers_tags,
        ciqual_food_name_tags,
        cities_tags,
        compared_to_category,
        correctors_tags,
        countries_tags,
        creator,
        data_quality_errors_tags,
        data_quality_info_tags,
        data_quality_warnings_tags,
        data_sources_tags,
        editors,
        emb_codes,
        emb_codes_tags,
        entry_dates_tags,
        environmental_score_data,
        environmental_score_grade,
        environmental_score_tags,
        food_groups_tags,
        generic_name,
        images,
        informers_tags,
        ingredients,
        ingredients_analysis_tags,
        ingredients_original_tags,
        ingredients_tags,
        ingredients_text,
        ingredients_without_ciqual_codes,
        labels,
        labels_tags,
        lang,
        languages_tags,
        last_edit_dates_tags,
        last_editor,
        last_modified_by,
        link,
        main_countries_tags,
        manufacturing_places,
        manufacturing_places_tags,
        minerals_tags,
        misc_tags,
        nova_groups,
        nova_groups_tags,
        nucleotides_tags,
        nutrient_levels_tags,
        nutriments,
        nutriscore_grade,
        nutrition_data_per,
        origins,
        origins_tags,
        owner,
        owner_fields,
        packaging,
        packaging_recycling_tags,
        packaging_shapes_tags,
        packaging_tags,
        packaging_text,
        packagings,
        photographers,
        popularity_tags,
        product_name,
        product_quantity,
        product_quantity_unit,
        purchase_places_tags,
        quantity,
        serving_quantity,
        serving_size,
        states_tags,
        stores,
        stores_tags,
        traces_tags,
        unknown_nutrients_tags,
        vitamins_tags,
 
        ---------- numerics
        additives_n,
        completeness,
        environmental_score_score,
        ingredients_from_palm_oil_n,
        ingredients_n,
        ingredients_percent_analysis,
        ingredients_with_specified_percent_n,
        ingredients_with_unspecified_percent_n,
        ingredients_without_ciqual_codes_n,
        known_ingredients_n,
        max_imgid,
        new_additives_n,
        nova_group,
        nutriscore_score,
        popularity_key,
        rev,
        scans_n,
        schema_version,
        unique_scans_n,
        unknown_ingredients_n,
 
        ---------- booleans
        with_non_nutritive_sweeteners as has_non_nutritive_sweeteners,
        with_sweeteners as has_sweeteners,
        complete as is_complete,
        no_nutrition_data as is_nutrition_data_missing,
        obsolete as is_obsolete,
        packagings_complete as is_packagings_complete,
 
        ---------- timestamps
        created_t as created_at,
        last_image_t as last_image_at,
        last_modified_t as last_modified_at,
        last_updated_t as last_updated_at

    from source

)

select * from renamed
